apiVersion: networking.cfargotunnel.com/v1alpha1
kind: ClusterTunnel
metadata:
  name: k3s-cluster-tunnel      # The ClusterTunnel Custom Resource Name
spec:
  newTunnel:
    name: hldo1-k8s-tunnel         # Name of your new tunnel on Cloudflare
  size: 2                       # This is the number of replicas for cloudflared
  cloudflare:
    email: jiri@kratochvil.eu
    domain: kratochvil.cloud         # Domain under which the tunnel runs and adds DNS entries to
    secret: cloudflare-secrets
    accountId: 433785da324c41f36fb7e30173e6c8f9