apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: wordpress-cluster-tunnel
  namespace: wordpress-blog
subjects:
  - name: wordpress
tunnelRef:
  kind: ClusterTunnel
  name: k3s-cluster-tunnel