repositories:
  - name: longhorn
    url: https://charts.longhorn.io
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: cloudflare
    url: https://cloudflare.github.io/helm-charts
#  - name: cowboysysop
#    url: https://cowboysysop.github.io/charts/

releases:
  # Distributed storage
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.7.1
    values:
    - values/longhorn.yaml

  # Wordpress blog
  - name: wordpress
    namespace: wordpress-blog
    chart: bitnami/wordpress
    version: 23.1.17
    values:
      - values/wordpress-blog.yaml
    hooks:
    - events: ["postSync"]
      showlogs: true
      command: "kubectl"
      args: ["apply", "-f", "ingress/wordpress-blog.yaml"]

#  - name: whoami
#    namespace: whoami
#    chart: cowboysysop/whoami
#    hooks:
#      - events: ["postSync"]
#        showlogs: true
#        command: "kubectl"
#        args: ["apply", "-f", "ingress/whoami.yaml"]



hooks:
  - events: ["prepare"]
    showlogs: true
    # kubectl apply -k https://github.com/adyanth/cloudflare-operator/config/default
    command: kubectl
    args:
      - apply
      - -k
      - https://github.com/adyanth/cloudflare-operator/config/default
  - events: ["prepare"]
    showlogs: true
    command: kubectl
    args:
      - apply
      - -k
      - ../kustomize