repositories:
  - name: longhorn
    url: https://charts.longhorn.io
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: cloudflare
    url: https://cloudflare.github.io/helm-charts
  - name: cowboysysop
    url: https://cowboysysop.github.io/charts/
  - name: k8s-home-lab
    url: https://k8s-home-lab.github.io/helm-charts/

releases:
  # Distributed storage
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.7.1
    values:
    - values/longhorn.yaml

  # Wordpress blog
  - name: wordpress
    namespace: wordpress-blog
    chart: bitnami/wordpress
    version: 23.1.17
    values:
      - values/wordpress-blog.yaml
    hooks:
    - events: ["postSync"]
      showlogs: true
      command: "kubectl"
      args: ["apply", "-f", "ingress/wordpress-blog.yaml"]

  - name: whoami
    namespace: whoami
    chart: cowboysysop/whoami
    hooks:
      - events: ["postSync"]
        showlogs: true
        command: "kubectl"
        args: ["apply", "-f", "ingress/whoami.yaml"]

  - name: books
    namespace: calibre-web
    chart: k8s-home-lab/calibre-web
    values:
      - env:
          TZ: "Europe/Prague"
      - persistence:
          config:
            enabled: true
            storageClass: longhorn
            size: 1Gi
            accessMode: ReadWriteOnce
            mountPath: /config
          books:
            enabled: true
            storageClass: longhorn
            size: 10Gi
            accessMode: ReadWriteOnce
            mountPath: /books
hooks:
  - events: ["prepare"]
    showlogs: true
    # kubectl apply -k https://github.com/adyanth/cloudflare-operator/config/default
    command: kubectl
    args:
      - apply
      - -k
      - https://github.com/adyanth/cloudflare-operator/config/default
  - events: ["prepare"]
    showlogs: true
    command: kubectl
    args:
      - apply
      - -k
      - ../kustomize