repositories:
  - name: longhorn
    url: https://charts.longhorn.io
  - name: bitnami
    url: https://charts.bitnami.com/bitnami


releases:
  # Distributed storage
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.7.1
  # Wordpress blog
  - name: my-wordpress
    namespace: wordpress-blog
    chart: bitnami/wordpress
    version: 23.1.17
    values:
      - values/wordpress-blog.yaml

